#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessTracker.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="FitnessTracker")]
	public partial class FitnessTrackerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertExerciseType(ExerciseType instance);
    partial void UpdateExerciseType(ExerciseType instance);
    partial void DeleteExerciseType(ExerciseType instance);
    partial void InsertWorkout(Workout instance);
    partial void UpdateWorkout(Workout instance);
    partial void DeleteWorkout(Workout instance);
    partial void InsertWorkoutRegimen(WorkoutRegimen instance);
    partial void UpdateWorkoutRegimen(WorkoutRegimen instance);
    partial void DeleteWorkoutRegimen(WorkoutRegimen instance);
    #endregion
		
		public FitnessTrackerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FitnessTrackerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessTrackerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessTrackerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessTrackerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessTrackerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ExerciseType> ExerciseTypes
		{
			get
			{
				return this.GetTable<ExerciseType>();
			}
		}
		
		public System.Data.Linq.Table<Workout> Workouts
		{
			get
			{
				return this.GetTable<Workout>();
			}
		}
		
		public System.Data.Linq.Table<WorkoutRegimen> WorkoutRegimens
		{
			get
			{
				return this.GetTable<WorkoutRegimen>();
			}
		}
	}
	
	[Table(Name="dbo.ExerciseTypes")]
	public partial class ExerciseType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExerciseTypeId;
		
		private string _Name;
		
		private EntitySet<WorkoutRegimen> _WorkoutRegimens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExerciseTypeIdChanging(int value);
    partial void OnExerciseTypeIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public ExerciseType()
		{
			this._WorkoutRegimens = new EntitySet<WorkoutRegimen>(new Action<WorkoutRegimen>(this.attach_WorkoutRegimens), new Action<WorkoutRegimen>(this.detach_WorkoutRegimens));
			OnCreated();
		}
		
		[Column(Storage="_ExerciseTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExerciseTypeId
		{
			get
			{
				return this._ExerciseTypeId;
			}
			set
			{
				if ((this._ExerciseTypeId != value))
				{
					this.OnExerciseTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ExerciseTypeId = value;
					this.SendPropertyChanged("ExerciseTypeId");
					this.OnExerciseTypeIdChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Association(Name="ExerciseType_WorkoutRegimen", Storage="_WorkoutRegimens", ThisKey="ExerciseTypeId", OtherKey="ExerciseTypeId")]
		public EntitySet<WorkoutRegimen> WorkoutRegimens
		{
			get
			{
				return this._WorkoutRegimens;
			}
			set
			{
				this._WorkoutRegimens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_WorkoutRegimens(WorkoutRegimen entity)
		{
			this.SendPropertyChanging();
			entity.ExerciseType = this;
		}
		
		private void detach_WorkoutRegimens(WorkoutRegimen entity)
		{
			this.SendPropertyChanging();
			entity.ExerciseType = null;
		}
	}
	
	[Table(Name="dbo.Workouts")]
	public partial class Workout : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WorkoutId;
		
		private int _WorkoutRegimenId;
		
		private System.DateTime _Date;
		
		private double _Pace;
		
		private int _Duration;
		
		private EntityRef<WorkoutRegimen> _WorkoutRegimen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWorkoutIdChanging(int value);
    partial void OnWorkoutIdChanged();
    partial void OnWorkoutRegimenIdChanging(int value);
    partial void OnWorkoutRegimenIdChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnPaceChanging(double value);
    partial void OnPaceChanged();
    partial void OnDurationChanging(int value);
    partial void OnDurationChanged();
    #endregion
		
		public Workout()
		{
			this._WorkoutRegimen = default(EntityRef<WorkoutRegimen>);
			OnCreated();
		}
		
		[Column(Storage="_WorkoutId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int WorkoutId
		{
			get
			{
				return this._WorkoutId;
			}
			set
			{
				if ((this._WorkoutId != value))
				{
					this.OnWorkoutIdChanging(value);
					this.SendPropertyChanging();
					this._WorkoutId = value;
					this.SendPropertyChanged("WorkoutId");
					this.OnWorkoutIdChanged();
				}
			}
		}
		
		[Column(Storage="_WorkoutRegimenId", DbType="Int NOT NULL")]
		public int WorkoutRegimenId
		{
			get
			{
				return this._WorkoutRegimenId;
			}
			set
			{
				if ((this._WorkoutRegimenId != value))
				{
					if (this._WorkoutRegimen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWorkoutRegimenIdChanging(value);
					this.SendPropertyChanging();
					this._WorkoutRegimenId = value;
					this.SendPropertyChanged("WorkoutRegimenId");
					this.OnWorkoutRegimenIdChanged();
				}
			}
		}
		
		[Column(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[Column(Storage="_Pace", DbType="Float NOT NULL")]
		public double Pace
		{
			get
			{
				return this._Pace;
			}
			set
			{
				if ((this._Pace != value))
				{
					this.OnPaceChanging(value);
					this.SendPropertyChanging();
					this._Pace = value;
					this.SendPropertyChanged("Pace");
					this.OnPaceChanged();
				}
			}
		}
		
		[Column(Storage="_Duration", DbType="Int NOT NULL")]
		public int Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this.OnDurationChanging(value);
					this.SendPropertyChanging();
					this._Duration = value;
					this.SendPropertyChanged("Duration");
					this.OnDurationChanged();
				}
			}
		}
		
		[Association(Name="WorkoutRegimen_Workout", Storage="_WorkoutRegimen", ThisKey="WorkoutRegimenId", OtherKey="WorkoutRegimenId", IsForeignKey=true)]
		public WorkoutRegimen WorkoutRegimen
		{
			get
			{
				return this._WorkoutRegimen.Entity;
			}
			set
			{
				WorkoutRegimen previousValue = this._WorkoutRegimen.Entity;
				if (((previousValue != value) 
							|| (this._WorkoutRegimen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WorkoutRegimen.Entity = null;
						previousValue.Workouts.Remove(this);
					}
					this._WorkoutRegimen.Entity = value;
					if ((value != null))
					{
						value.Workouts.Add(this);
						this._WorkoutRegimenId = value.WorkoutRegimenId;
					}
					else
					{
						this._WorkoutRegimenId = default(int);
					}
					this.SendPropertyChanged("WorkoutRegimen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.WorkoutRegimens")]
	public partial class WorkoutRegimen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WorkoutRegimenId;
		
		private int _ExerciseTypeId;
		
		private string _Person;
		
		private System.DateTime _StartDate;
		
		private int _NumWeeks;
		
		private int _DaysPerWeek;
		
		private double _StartingPace;
		
		private System.Nullable<double> _FinishingPace;
		
		private int _StartingDuration;
		
		private System.Nullable<int> _FinishingDuration;
		
		private EntitySet<Workout> _Workouts;
		
		private EntityRef<ExerciseType> _ExerciseType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWorkoutRegimenIdChanging(int value);
    partial void OnWorkoutRegimenIdChanged();
    partial void OnExerciseTypeIdChanging(int value);
    partial void OnExerciseTypeIdChanged();
    partial void OnPersonChanging(string value);
    partial void OnPersonChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnNumWeeksChanging(int value);
    partial void OnNumWeeksChanged();
    partial void OnDaysPerWeekChanging(int value);
    partial void OnDaysPerWeekChanged();
    partial void OnStartingPaceChanging(double value);
    partial void OnStartingPaceChanged();
    partial void OnFinishingPaceChanging(System.Nullable<double> value);
    partial void OnFinishingPaceChanged();
    partial void OnStartingDurationChanging(int value);
    partial void OnStartingDurationChanged();
    partial void OnFinishingDurationChanging(System.Nullable<int> value);
    partial void OnFinishingDurationChanged();
    #endregion
		
		public WorkoutRegimen()
		{
			this._Workouts = new EntitySet<Workout>(new Action<Workout>(this.attach_Workouts), new Action<Workout>(this.detach_Workouts));
			this._ExerciseType = default(EntityRef<ExerciseType>);
			OnCreated();
		}
		
		[Column(Storage="_WorkoutRegimenId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int WorkoutRegimenId
		{
			get
			{
				return this._WorkoutRegimenId;
			}
			set
			{
				if ((this._WorkoutRegimenId != value))
				{
					this.OnWorkoutRegimenIdChanging(value);
					this.SendPropertyChanging();
					this._WorkoutRegimenId = value;
					this.SendPropertyChanged("WorkoutRegimenId");
					this.OnWorkoutRegimenIdChanged();
				}
			}
		}
		
		[Column(Storage="_ExerciseTypeId", DbType="Int NOT NULL")]
		public int ExerciseTypeId
		{
			get
			{
				return this._ExerciseTypeId;
			}
			set
			{
				if ((this._ExerciseTypeId != value))
				{
					if (this._ExerciseType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExerciseTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ExerciseTypeId = value;
					this.SendPropertyChanged("ExerciseTypeId");
					this.OnExerciseTypeIdChanged();
				}
			}
		}
		
		[Column(Storage="_Person", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Person
		{
			get
			{
				return this._Person;
			}
			set
			{
				if ((this._Person != value))
				{
					this.OnPersonChanging(value);
					this.SendPropertyChanging();
					this._Person = value;
					this.SendPropertyChanged("Person");
					this.OnPersonChanged();
				}
			}
		}
		
		[Column(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[Column(Storage="_NumWeeks", DbType="Int NOT NULL")]
		public int NumWeeks
		{
			get
			{
				return this._NumWeeks;
			}
			set
			{
				if ((this._NumWeeks != value))
				{
					this.OnNumWeeksChanging(value);
					this.SendPropertyChanging();
					this._NumWeeks = value;
					this.SendPropertyChanged("NumWeeks");
					this.OnNumWeeksChanged();
				}
			}
		}
		
		[Column(Storage="_DaysPerWeek", DbType="Int NOT NULL")]
		public int DaysPerWeek
		{
			get
			{
				return this._DaysPerWeek;
			}
			set
			{
				if ((this._DaysPerWeek != value))
				{
					this.OnDaysPerWeekChanging(value);
					this.SendPropertyChanging();
					this._DaysPerWeek = value;
					this.SendPropertyChanged("DaysPerWeek");
					this.OnDaysPerWeekChanged();
				}
			}
		}
		
		[Column(Storage="_StartingPace", DbType="Float NOT NULL")]
		public double StartingPace
		{
			get
			{
				return this._StartingPace;
			}
			set
			{
				if ((this._StartingPace != value))
				{
					this.OnStartingPaceChanging(value);
					this.SendPropertyChanging();
					this._StartingPace = value;
					this.SendPropertyChanged("StartingPace");
					this.OnStartingPaceChanged();
				}
			}
		}
		
		[Column(Storage="_FinishingPace", DbType="Float")]
		public System.Nullable<double> FinishingPace
		{
			get
			{
				return this._FinishingPace;
			}
			set
			{
				if ((this._FinishingPace != value))
				{
					this.OnFinishingPaceChanging(value);
					this.SendPropertyChanging();
					this._FinishingPace = value;
					this.SendPropertyChanged("FinishingPace");
					this.OnFinishingPaceChanged();
				}
			}
		}
		
		[Column(Storage="_StartingDuration", DbType="Int NOT NULL")]
		public int StartingDuration
		{
			get
			{
				return this._StartingDuration;
			}
			set
			{
				if ((this._StartingDuration != value))
				{
					this.OnStartingDurationChanging(value);
					this.SendPropertyChanging();
					this._StartingDuration = value;
					this.SendPropertyChanged("StartingDuration");
					this.OnStartingDurationChanged();
				}
			}
		}
		
		[Column(Storage="_FinishingDuration", DbType="Int")]
		public System.Nullable<int> FinishingDuration
		{
			get
			{
				return this._FinishingDuration;
			}
			set
			{
				if ((this._FinishingDuration != value))
				{
					this.OnFinishingDurationChanging(value);
					this.SendPropertyChanging();
					this._FinishingDuration = value;
					this.SendPropertyChanged("FinishingDuration");
					this.OnFinishingDurationChanged();
				}
			}
		}
		
		[Association(Name="WorkoutRegimen_Workout", Storage="_Workouts", ThisKey="WorkoutRegimenId", OtherKey="WorkoutRegimenId")]
		public EntitySet<Workout> Workouts
		{
			get
			{
				return this._Workouts;
			}
			set
			{
				this._Workouts.Assign(value);
			}
		}
		
		[Association(Name="ExerciseType_WorkoutRegimen", Storage="_ExerciseType", ThisKey="ExerciseTypeId", OtherKey="ExerciseTypeId", IsForeignKey=true)]
		public ExerciseType ExerciseType
		{
			get
			{
				return this._ExerciseType.Entity;
			}
			set
			{
				ExerciseType previousValue = this._ExerciseType.Entity;
				if (((previousValue != value) 
							|| (this._ExerciseType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ExerciseType.Entity = null;
						previousValue.WorkoutRegimens.Remove(this);
					}
					this._ExerciseType.Entity = value;
					if ((value != null))
					{
						value.WorkoutRegimens.Add(this);
						this._ExerciseTypeId = value.ExerciseTypeId;
					}
					else
					{
						this._ExerciseTypeId = default(int);
					}
					this.SendPropertyChanged("ExerciseType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Workouts(Workout entity)
		{
			this.SendPropertyChanging();
			entity.WorkoutRegimen = this;
		}
		
		private void detach_Workouts(Workout entity)
		{
			this.SendPropertyChanging();
			entity.WorkoutRegimen = null;
		}
	}
}
#pragma warning restore 1591
